using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class RecipeGenerator : MonoBehaviour
{
    private List<string> generatedRecipe;   //The recipe generated by GenerateRecipe()
    private List<string> chosenIngredients; //The list of ingredients that the player has chosen in this round

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }


    /// <summary>
    /// Generates a new Recipe based on the difficulty and the number of players
    /// Easy = 4 Items (+1 item for every player over 4)
    /// Medium = 5 Items (+1 item for every player over 5)
    /// Hard = 7 Items (+1 item for every player over 7, up to a max of 8)
    /// </summary>
    /// <returns></returns>
    public List<string> GenerateRecipe()
    {
        return null;
    }


    /// <summary>
    /// Selects 4 random ingredients from a category, and compiles them into an array
    /// One of the "random" ingredients must be an item from the generatedRecipe
    /// None of these items should be in both the chosenIngredients and generatedRecipe lists
    /// </summary>
    /// <returns></returns>
    public List<string> PickRandomIngredients()
    {
        // This function needs to pick one of the correct ingredients, and make sure it is displayed, along with three other ingredients
        return null;
    }

    /// <summary>
    /// Called when the user chooses an ingredient to add to the recipe
    /// Adds a new ingredient to the list of chosenIngredients
    /// </summary>
    /// <param name="newIngredient"></param>
    public void AddChosenIngredient(string newIngredient)
    {
        chosenIngredients.Add(newIngredient);
    }
}
